Tiempo de Traslado y eliminar viajes 15 s
saturdaysai-gdl2-plata/datasets pull request #3
Opened 2020-05-30 05:36 UTC by rocsx

Se agrego un nueva columna llamada diff_seconds en donde esta el tiempo en segundos de cada traslado, asi mismo una ves teniendo ese resultado se elimino todo las filas que fueran menosros a 15 segundos.

2020-05-30 16:07 UTC, ivanovishado requested changes
Buen approach. Muy limpio. Sólo corrige los comentarios para darle merge.

2020-05-30 16:07 UTC, ivanovishado commented on eda_mibici.py
> +df.shape
Creo que se puede quitar esta línea, porque no se está haciendo uso del valor que regresa `shape`

2020-05-30 16:07 UTC, ivanovishado commented on eda_mibici.py
> +df.shape
Mismo comentario.

2020-05-30 16:07 UTC, ivanovishado commented on eda_mibici.py
> +from datetime import date
No necesitaremos estos imports para cuando se mergee el otro PR.

2020-05-30 16:07 UTC, ivanovishado commented on eda_mibici.py
> +df['diff_seconds']= df['diff_seconds']/np.timedelta64(1,'s')
```suggestion
df['diff_seconds'] = (df['Fin_del_viaje'] - df['Inicio_del_viaje']).astype('timedelta64[s]')
```

Me parece que desde un inicio podemos decirle de qué tipo queremos que sea la resta, sin necesidad de hacer la división.

2020-06-04 02:30 UTC, rocsx commented on eda_mibici.py
> +df.shape
Se elimino  shape

2020-06-19 00:17 UTC, ivanovishado approved these changes

2020-06-19 00:22 UTC, merged