Coordenadas de estaciones
saturdaysai-gdl2-plata/datasets pull request #8
Opened 2020-06-12 23:09 UTC by dpadilla93

2020-06-19 01:48 UTC, ivanovishado requested changes

2020-06-19 01:48 UTC, ivanovishado commented on eda_mibici.py
> +df.Destino_Coord.isna().sum()
Me parece que no necesitamos estas líneas.

2020-06-19 01:48 UTC, ivanovishado commented on eda_mibici.py
> +location = {2:'20.666378,-103.34882',
Nos dimos cuenta que necesitamos un approach un poco distinto.

Si bien el objetivo de esta tarea se cumplió al poner las coordenadas de esta manera, será mucho más útil para poder seguir avanzando que se genere un `DataFrame` aparte con esta información.

Creo que hay maneras simples de convertir un `dict` a `DataFrame`, aunque creo que la parte complicada será separar la latitud y longitud para que queden en columnas independientes. Esto es de mucha ayuda tanto para el modelo que vamos a generar como para calcular la distancia entre colonias y estaciones.

2020-06-20 15:53 UTC, dpadilla93 commented on eda_mibici.py
> +location = {2:'20.666378,-103.34882',
Ok, necesitamos un DF distinto? No hay problema

2020-06-20 18:10 UTC, ivanovishado commented
Cerrando en favor del trabajo realizado en #13

2020-06-20 18:10 UTC, closed without merging